version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18-bullseye
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build Docker Image
          command: docker build -t sample-app .
      - run:
          name: List Docker Images
          command: docker images

  push:
    docker:
      - image: circleci/node:18-bullseye
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/sample-app:latest .
            docker push $DOCKERHUB_USERNAME/sample-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: main
