version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-node-app:latest .
      - run:
          name: List Docker Images
          command: docker images
      - run:
          name: Run Docker Container
          command: docker run -d --name sample-container my-node-app
      - run:
          name: Test Ping
          command: docker exec sample-container ping -c 4 127.0.0.1

  push:
    docker:
      - image: cimg/base:stable  # Image avec Docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/sample-app:latest .
            docker push $DOCKERHUB_USERNAME/sample-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: main