version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  commit:
    jobs:
      - docker/publish:
        image: $DOCKERHUB_USERNAME/my-node-app
        docker-username: $DOCKERHUB_USERNAME
        docker-password: $DOCKERHUB_ACCESS_TOKEN

