version: 2.1

orbs:
  docker: circleci/docker@2.3.0 

jobs:
  build-and-push:
    machine:
      image: ubuntu-2204:current 

    steps:
      - checkout

      - docker/build:
          image: $DOCKERHUB_USERNAME/my-node-app
          tag: latest

      - docker/push:
          image: $DOCKERHUB_USERNAME/my-node-app
          tag: latest
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-push