version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  build-and-publish:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_USERNAME/my-node-app
          tag: latest
          docker-password: DOCKERHUB_ACCESS_TOKEN
          docker-username: DOCKERHUB_USERNAME

