version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - checkout
      - run:
          name: Installer Node.js 18
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v  # Vérifier la version de Node.js
            npm -v   # Vérifier la version de npm
      - run:
          name: Installer les dépendances
          command: |
            npm install
      - run:
          name: Construire l'image Docker
          command: |
            docker build -t my-node-app:latest .
      - run:
          name: Lister les images Docker
          command: docker images
      - run:
          name: Exécuter le conteneur Docker
          command: docker run -d -p 8080:8080 --name sample-container my-node-app
      - run:
          name: Tester l'application avec Curl
          command: |
            sleep 5  # Attendre que le service démarre
            curl -f http://localhost:8080 || (docker logs sample-container && exit 1)
      - run:
          name: Se connecter à Docker Hub
          command: echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Pousser l'image Docker
          command: |
            docker push $DOCKERHUB_USERNAME/my-node-app:latest


workflows:
  version: 2
  build_and_push:
    jobs:
      - build