name: Docker CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: debian-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Run container
        run: docker run -d -p 8080:8080 --name sample-container my-node-app

      - name: Test with curl
        run: |
          sleep 5  # Attendre que le service démarre
          curl -f http://localhost:8080 || (docker logs sample-container && exit 1)

  push:
    needs: build
    runs-on: debian-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest
